### ISSUE TITLE
precomputed option for Hubness with hnsw not working

### ISSUE THREAD

**Issue by ivan-marroquin** [VarIr/scikit-hubness#71]
Hi,

I would like to report the following issue with precomputed option when using hnsw algorithm. 

First run:

``` python3
import numpy as np
from skhubness import Hubness
from skhubness.neighbors import VALID_METRICS
from sklearn.metrics import pairwise_distances

X= np.random.randn(100,7)
dist= pairwise_distances(X, metric= 'minkowski', p= 0.1)
hub= Hubness(k= 15, return_value= 'all', metric= 'precomputed', algorithm= 'hnsw', hubness= None, random_state= 1969, n_jobs= 3)
hub.fit(dist)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\scikit_hubness-0.21.3-py3.6.egg\skhubness\analysis\estimation.py", line 325, in fit
    verbose=self.verbose,
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\scikit_hubness-0.21.3-py3.6.egg\skhubness\neighbors\unsupervised.py", line 163, in __init__
    metric_params=metric_params, n_jobs=n_jobs, **kwargs)
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\scikit_hubness-0.21.3-py3.6.egg\skhubness\neighbors\base.py", line 155, in __init__
    n_jobs=n_jobs)
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\sklearn\neighbors\base.py", line 121, in __init__
    self._check_algorithm_metric()
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\scikit_hubness-0.21.3-py3.6.egg\skhubness\neighbors\base.py", line 214, in _check_algorithm_metric
    raise ValueError(f"Metric '{self.metric}' not valid. Use "
ValueError: Metric 'precomputed' not valid. Use sorted(skhubness.neighbors.VALID_METRICS['hnsw']) to get valid options. Metric can also be a callable function.
```
Second run:
``` python3
print(VALID_METRICS['hnsw']) 
['euclidean', 'l2', 'minkowski', 'squared_euclidean', 'sqeuclidean', 'cosine', 'cosinesimil']

hub= Hubness(k= 15, return_value= 'all', metric= 'minkowski', p= 0.1, algorithm= 'hnsw', hubness= None, random_state= 1969, n_jobs= 3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'p'
```
Third run:
``` python3
hub= Hubness(k= 15, return_value= 'all', metric= 'minkowski', algorithm= 'hnsw', algorithm_params= {'p': 0.1}, hubness= None, random_state= 1969, n_jobs= 3)
hub.fit(dist)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\scikit_hubness-0.21.3-py3.6.egg\skhubness\analysis\estimation.py", line 283, in fit
    raise ValueError(f"Unknown metric '{metric}'. "
ValueError: Unknown metric 'minkowski'. Must be one of ['euclidean', 'cosine', 'precomputed'].
```
Thanks for your help,

Ivan

**Comment by VarIr** [comment]
It seems the error messages are sometimes misleading. In any case, `metric="precomputed"` should be combined with `algorithm="brute"`.

**Comment by ivan-marroquin** [comment]
Unfortunately, the help documentation does not mention that 'precomputed' should be used with algorithm set to 'brute' (https://scikit-hubness.readthedocs.io/en/latest/documentation/_autosummary/skhubness.analysis.Hubness.html)

**Comment by VarIr** [comment]
Starting from v0.30, `Hubness` will by default expect [`KNeighborsTransformer`](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsTransformer.html)-compatible input, that is, a sparse k-neighbors graph as produced by recent versions of sklearn or the new wrappers in skhubness (e.g. the [`NMSlibTransformer`](https://github.com/VarIr/scikit-hubness/blob/v0.30/skhubness/neighbors/_nmslib.py#L30)).

This should effectively solve this issue.
